#!/bin/sh

set -e

if [ "$1" = "--help" ]; then
  echo "usage: $PROGNAME [STAGE]" >&2
  echo >&2
  echo "Deploy artifact to stage STAGE. If omitted, STAGE is inferred." >&2
  exit 1
fi

if [ "$1" ]; then
  stage="$1"
elif [ "$TRAVIS_PULL_REQUEST" -a "$TRAVIS_PULL_REQUEST" != "false" ]; then
  #stage="pr$TRAVIS_PULL_REQUEST"
  echo "Not deploying on pull request, AWS credentials not available"
  exit 0
elif [ "$TRAVIS_BRANCH" ]; then
  stage="$TRAVIS_BRANCH"
else
  stage=`git rev-parse --abbrev-ref HEAD`
fi

stage=`echo "$stage" | sed -e 's#^.*/##' | tr '.-' '_'`
bucket=goabout-artifacts
prefix=opentripplanner/$stage

delete() {
  aws --quiet s3 rm --recursive s3://$bucket/$prefix
  echo "delete: $bucket/$prefix"
}

put() {
  src="$1"
  dst="$2"

  md5=`openssl dgst -md5 -binary "$src" | openssl enc -base64`
  aws s3api put-object --bucket $bucket --key "$prefix/$dst" \
                       --body "$src" --content-md5 $md5 > /dev/null
  echo "put: $bucket/$prefix/$dst"
}

echo "Deploying to $bucket/$prefix"
export AWS_CONFIG_FILE=.aws_config
delete
put otp-core/target/otp.jar otp.jar
put deploy_vars.yml ansible_vars.yml
